path_classifiers:
  test:
    - "test/*.cpp"
extraction:
  cpp:
    prepare:
      packages:
        - cmake
        - g++-8
        - ninja-build
    after_prepare:
      - mkdir -p $LGTM_WORKSPACE/latest-gcc-symlinks
      - ln -s /usr/bin/g++-8 $LGTM_WORKSPACE/latest-gcc-symlinks/g++
      - ln -s /usr/bin/gcc-8 $LGTM_WORKSPACE/latest-gcc-symlinks/gcc
      - export PATH=$LGTM_WORKSPACE/latest-gcc-symlinks:$PATH
