dist: xenial
services: [docker]
language: cpp
env:
  - TEST_SUITE=release
  - TEST_SUITE=asan
  - TEST_SUITE=ubsan
  - TEST_SUITE=release:gnu
install:
  - docker pull gregjm/cpp-build
  - docker build --tag function2 .
script:
  - docker run --privileged --rm function2 "${TEST_SUITE}"
jobs:
  include:
    - stage: deploy
      if: branch = master
      services: []
      before_install:
        - sudo apt-get install -y doxygen
      install:
        - true
      script:
        - mkdir build
        - cd build
        - cmake .. -DFUNCTION2_BUILD_DOCS=ON
        - cmake --build . --target doc
        - cd ..
      env: TEST_SUITE=""
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          on:
            branch: master
          local-dir: build/doc/html
